import {
    StatusBar as NativeStatusBar,
    Platform,
    StyleSheet,
} from 'react-native';

import {
    NAVIENTY_NOW_COLORS,
    NAVIENTY_NOW_LAYOUT,
} from '../../theme/navienty-now-theme';

const HOME_BANNER_HEIGHT_SCALE = 1.1;

export const styles = StyleSheet.create({
  screen: {
      backgroundColor: NAVIENTY_NOW_COLORS.page,
      flex: 1,
  },
  pageContent: {
      paddingBottom: NAVIENTY_NOW_LAYOUT.bottomNavigationHeight +
          48,
  },
  header: {
      backgroundColor: NAVIENTY_NOW_COLORS.primary,
      minHeight: 172,
      overflow: 'hidden',
      position: 'relative',
      width: '100%',
  },
  headerTimeMoodLayer: {
      bottom: 0,
      left: 0,
      overflow: 'hidden',
      position: 'absolute',
      right: 0,
      top: 0,
      zIndex: 1,
  },
  headerTimeMoodBackground: {
      bottom: 0,
      height: '100%',
      left: 0,
      position: 'absolute',
      right: 0,
      top: 0,
      width: '100%',
  },
  nightMoon: {
      backgroundColor: 'rgba(235,255,244,0.94)',
      borderRadius: 999,
      height: 22,
      left: '8%',
      position: 'absolute',
      top: 31,
      width: 22,
  },
  nightMoonCutout: {
      backgroundColor: '#0B463F',
      borderRadius: 999,
      height: 20,
      left: 7,
      position: 'absolute',
      top: -2,
      width: 20,
  },
  nightStar: {
      backgroundColor: 'rgba(235,255,244,0.82)',
      borderRadius: 999,
      height: 3,
      position: 'absolute',
      width: 3,
  },
  nightStarOne: {
      left: '16%',
      top: 24,
  },
  nightStarTwo: {
      height: 2,
      left: '20%',
      top: 43,
      width: 2,
  },
  nightStarThree: {
      height: 2,
      left: '12%',
      top: 58,
      width: 2,
  },
  morningGlow: {
      backgroundColor: 'rgba(221,255,190,0.10)',
      borderRadius: 999,
      height: 122,
      left: '23%',
      position: 'absolute',
      top: -48,
      width: 122,
  },
  morningSun: {
      backgroundColor: 'rgba(232,255,203,0.78)',
      borderColor: 'rgba(255,255,255,0.42)',
      borderRadius: 999,
      borderWidth: 1,
      height: 17,
      left: '31%',
      position: 'absolute',
      top: 29,
      width: 17,
  },
  dayGlow: {
      backgroundColor: 'rgba(255,255,255,0.055)',
      borderRadius: 999,
      height: 220,
      left: '41%',
      position: 'absolute',
      top: -108,
      width: 220,
  },
  sunsetGlow: {
      backgroundColor: 'rgba(255,183,118,0.10)',
      borderRadius: 999,
      height: 178,
      position: 'absolute',
      right: -28,
      top: -48,
      width: 178,
  },
  sunsetSun: {
      backgroundColor: 'rgba(255,202,137,0.72)',
      borderColor: 'rgba(255,233,202,0.48)',
      borderRadius: 999,
      borderWidth: 1,
      bottom: 76,
      height: 19,
      position: 'absolute',
      right: '12%',
      width: 19,
  },
  moodHorizonVeil: {
      backgroundColor: 'rgba(0,69,43,0.055)',
      bottom: 58,
      height: 22,
      left: 0,
      position: 'absolute',
      right: 0,
  },
  // Abstract road: a darker green ribbon with very soft lane markers.
  // It is intentionally subtle so the courier remains the visual focus.
  headerRoadLayer: {
      bottom: 12,
      height: 58,
      left: -22,
      position: 'absolute',
      right: -22,
      zIndex: 2,
  },
  headerRoadSurface: {
      backgroundColor: 'rgba(0,50,39,0.29)',
      borderColor: 'rgba(255,255,255,0.07)',
      borderRadius: 999,
      borderWidth: 1,
      bottom: 0,
      height: 48,
      left: 0,
      position: 'absolute',
      right: 0,
  },
  headerRoadHighlight: {
      backgroundColor: 'rgba(255,255,255,0.075)',
      borderRadius: 999,
      height: 1,
      left: 28,
      position: 'absolute',
      right: 28,
      top: 9,
  },
  headerRoadDashTrack: {
      flexDirection: 'row',
      left: -384,
      position: 'absolute',
      top: 30,
      width: 1344,
  },
  headerRoadDash: {
      backgroundColor: 'rgba(255,255,255,0.30)',
      borderRadius: 999,
      height: 3,
      marginRight: 62,
      width: 34,
  },
  // The bike begins fully beyond the right edge, crosses every 24h mood,
  // then exits beyond the left edge before the invisible loop reset.
  deliveryBikeTrack: {
      bottom: 11,
      height: 132,
      position: 'absolute',
      right: -176,
      width: 166,
      zIndex: 6,
  },
  // Android mirrors the iOS physical journey inside a clipped full-width
  // layer. The bike begins completely outside the right edge, crosses the
  // header, exits completely outside the left edge, then resets invisibly.
  androidBikeLayer: {
      bottom: 0,
      direction: 'ltr',
      elevation: 40,
      left: 0,
      overflow: 'hidden',
      position: 'absolute',
      right: 0,
      top: 0,
      zIndex: 40,
  },
  androidBikeTrack: {
      bottom: 11,
      height: 132,
      left: 0,
      position: 'absolute',
      width: 166,
  },
  deliveryBikeShadow: {
      backgroundColor: 'rgba(0,45,28,0.18)',
      borderRadius: 999,
      bottom: 8,
      height: 9,
      left: 25,
      position: 'absolute',
      right: 17,
      transform: [{ scaleX: 0.9 }],
  },
  deliveryBikeImage: {
      height: 132,
      width: 166,
  },
  contentShell: {
      alignSelf: 'center',
      paddingHorizontal: NAVIENTY_NOW_LAYOUT.pageGutter,
      width: '100%',
  },
  homeSearchEntry: {
      alignItems: 'center',
      backgroundColor: '#F6F6F6',
      borderColor: '#E4E4E4',
      borderRadius: 999,
      borderWidth: StyleSheet.hairlineWidth,
      flexDirection: 'row-reverse',
      height: 42,
      marginTop: 8,
      paddingHorizontal: 13,
  },
  homeSearchEntryPressed: {
      backgroundColor: '#F1F1F1',
      opacity: 0.94,
  },
  homeSearchIconWrap: {
      alignItems: 'center',
      height: 26,
      justifyContent: 'center',
      marginLeft: 6,
      width: 22,
  },
  homeSearchPlaceholder: {
      color: '#303030',
      flex: 1,
      fontSize: 14,
      fontWeight: '500',
      letterSpacing: -0.1,
      textAlign: 'right',
      writingDirection: 'rtl',
  },
  homeSearchFixedText: {
      color: '#303030',
      fontWeight: '500',
  },
  homeSearchDynamicText: {
      color: '#696969',
      fontWeight: '500',
  },
  categoryList: {
      marginHorizontal: -NAVIENTY_NOW_LAYOUT.pageGutter,
      marginTop: 18,
  },
  categoryListContent: {
      alignItems: 'flex-start',
      flexDirection: 'row-reverse',
      flexGrow: 1,
      gap: 8,
      justifyContent: 'center',
      paddingHorizontal: NAVIENTY_NOW_LAYOUT.pageGutter,
      paddingVertical: 8,
  },
  categoryItem: {
      alignItems: 'center',
  },
  categoryItemPressed: {
      opacity: 0.72,
      transform: [{ scale: 0.975 }],
  },
  categoryArtwork: {
      alignItems: 'center',
      backgroundColor: NAVIENTY_NOW_COLORS.white,
      borderRadius: 25,
      height: 104,
      justifyContent: 'center',
      overflow: 'hidden',
      width: 104,
  },
  categoryImage: {
      height: '96%',
      width: '96%',
  },
  categoryLabel: {
      color: NAVIENTY_NOW_COLORS.text,
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 18,
      marginTop: 8,
      minHeight: 36,
      textAlign: 'center',
      writingDirection: 'rtl',
  },
  discoverySection: {
      marginTop: 26,
  },
  discoveryTitle: {
      color: NAVIENTY_NOW_COLORS.text,
      fontSize: 18,
      fontWeight: '900',
      letterSpacing: -0.35,
      textAlign: 'right',
      writingDirection: 'rtl',
  },
  discoveryRail: {
      marginHorizontal: -NAVIENTY_NOW_LAYOUT.pageGutter,
      marginTop: 15,
  },
  discoveryRailContent: {
      flexDirection: 'row-reverse',
      gap: 10,
      paddingBottom: 4,
      paddingHorizontal: NAVIENTY_NOW_LAYOUT.pageGutter,
  },
  discoveryCard: {
      alignItems: 'center',
      backgroundColor: NAVIENTY_NOW_COLORS.white,
      borderColor: '#DFE3E1',
      borderRadius: 20,
      borderWidth: 1,
      elevation: 1,
      flexShrink: 0,
      justifyContent: 'center',
      overflow: 'hidden',
      position: 'relative',
      shadowColor: '#000000',
      shadowOffset: {
          width: 0,
          height: 1,
      },
      shadowOpacity: 0.045,
      shadowRadius: 3,
  },
  discoveryCardPressed: {
      opacity: 0.82,
      transform: [
          {
              scale: 0.97,
          },
      ],
  },
  discoveryImage: {
      height: '100%',
      width: '100%',
  },
  primaryButtonPressed: {
      backgroundColor: NAVIENTY_NOW_COLORS.primaryPressed,
      opacity: 0.9,
      transform: [{ scale: 0.985 }],
  },
  /* ================================= */
  /* FOR YOU — SIMPLE PRODUCT TILE RAIL  */
  /* ================================= */
  forYouSection: {
      marginTop: 26,
  },
  forYouSectionTitle: {
      color: NAVIENTY_NOW_COLORS.text,
      fontSize: 18,
      fontWeight: '900',
      letterSpacing: -0.35,
      textAlign: 'right',
      writingDirection: 'rtl',
  },
  forYouRail: {
      marginHorizontal: -NAVIENTY_NOW_LAYOUT.pageGutter,
      marginTop: 15,
  },
  forYouRailContent: {
      flexDirection: 'row-reverse',
      gap: 10,
      paddingBottom: 4,
      paddingHorizontal: NAVIENTY_NOW_LAYOUT.pageGutter,
  },
  forYouCard: {
      alignItems: 'center',
      backgroundColor: NAVIENTY_NOW_COLORS.white,
      borderColor: '#DFE3E1',
      borderRadius: 20,
      borderWidth: 1,
      elevation: 1,
      flexShrink: 0,
      justifyContent: 'center',
      overflow: 'hidden',
      position: 'relative',
      shadowColor: '#000000',
      shadowOffset: {
          width: 0,
          height: 1,
      },
      shadowOpacity: 0.045,
      shadowRadius: 3,
  },
  forYouCardPressed: {
      opacity: 0.82,
      transform: [
          {
              scale: 0.97,
          },
      ],
  },
  forYouCardDisabled: {
      opacity: 0.86,
  },
  forYouArtwork: {
      alignItems: 'center',
      backgroundColor: NAVIENTY_NOW_COLORS.white,
      height: '100%',
      justifyContent: 'center',
      overflow: 'hidden',
      width: '100%',
  },
  forYouImage: {
      height: '100%',
      width: '100%',
  },
  forYouFallback: {
      fontSize: 32,
  },
  forYouLoadingOverlay: {
      alignItems: 'center',
      backgroundColor: 'rgba(255,255,255,0.78)',
      bottom: 0,
      justifyContent: 'center',
      left: 0,
      position: 'absolute',
      right: 0,
      top: 0,
  },
  /* ================================= */
  /* RECENTLY VIEWED — SIMPLE TILE RAIL */
  /* ================================= */
  recentlyViewedSection: {
      marginTop: 26,
  },
  recentlyViewedSectionTitle: {
      color: NAVIENTY_NOW_COLORS.text,
      fontSize: 18,
      fontWeight: '900',
      letterSpacing: -0.35,
      textAlign: 'right',
      writingDirection: 'rtl',
  },
  recentlyViewedRail: {
      marginHorizontal: -NAVIENTY_NOW_LAYOUT.pageGutter,
      marginTop: 15,
  },
  recentlyViewedRailContent: {
      flexDirection: 'row-reverse',
      gap: 10,
      paddingBottom: 4,
      paddingHorizontal: NAVIENTY_NOW_LAYOUT.pageGutter,
  },
  recentlyViewedCard: {
      alignItems: 'center',
      backgroundColor: NAVIENTY_NOW_COLORS.white,
      borderColor: '#DFE3E1',
      borderRadius: 20,
      borderWidth: 1,
      elevation: 1,
      flexShrink: 0,
      justifyContent: 'center',
      overflow: 'hidden',
      position: 'relative',
      shadowColor: '#000000',
      shadowOffset: {
          width: 0,
          height: 1,
      },
      shadowOpacity: 0.045,
      shadowRadius: 3,
  },
  recentlyViewedCardPressed: {
      opacity: 0.82,
      transform: [
          {
              scale: 0.97,
          },
      ],
  },
  recentlyViewedArtwork: {
      alignItems: 'center',
      backgroundColor: NAVIENTY_NOW_COLORS.white,
      height: '100%',
      justifyContent: 'center',
      overflow: 'hidden',
      width: '100%',
  },
  recentlyViewedImage: {
      height: '100%',
      width: '100%',
  },
  recentlyViewedFallback: {
      fontSize: 32,
  },
  /* ================================= */
  /* RECENT / ORDER AGAIN — LOGO RAIL    */
  /* ================================= */
  recentOrdersSection: {
      marginTop: 26,
  },
  recentOrdersTitle: {
      color: NAVIENTY_NOW_COLORS.text,
      fontSize: 18,
      fontWeight: '900',
      letterSpacing: -0.35,
      textAlign: 'right',
      writingDirection: 'rtl',
  },
  recentOrdersRail: {
      marginHorizontal: -NAVIENTY_NOW_LAYOUT.pageGutter,
      marginTop: 15,
  },
  recentOrdersRailContent: {
      flexDirection: 'row-reverse',
      gap: 10,
      paddingBottom: 4,
      paddingHorizontal: NAVIENTY_NOW_LAYOUT.pageGutter,
  },
  recentOrderCard: {
      alignItems: 'center',
      backgroundColor: NAVIENTY_NOW_COLORS.white,
      borderColor: '#DFE3E1',
      borderRadius: 20,
      borderWidth: 1,
      elevation: 1,
      flexShrink: 0,
      justifyContent: 'center',
      overflow: 'hidden',
      position: 'relative',
      shadowColor: '#000000',
      shadowOffset: {
          width: 0,
          height: 1,
      },
      shadowOpacity: 0.045,
      shadowRadius: 3,
  },
  recentOrderCardPressed: {
      opacity: 0.82,
      transform: [
          {
              scale: 0.97,
          },
      ],
  },
  recentOrderArtwork: {
      alignItems: 'center',
      backgroundColor: NAVIENTY_NOW_COLORS.white,
      height: '100%',
      justifyContent: 'center',
      overflow: 'hidden',
      width: '100%',
  },
  recentOrderArtworkImage: {
      height: '100%',
      width: '100%',
  },
  recentOrderArtworkLoading: {
      backgroundColor: '#F3F5F4',
      height: '100%',
      width: '100%',
  },
  recentOrderArtworkFallback: {
      fontSize: 32,
  },
  /* ================================= */
  /* ACTIVE ORDER TRACKING               */
  /* ================================= */
  activeOrdersRail: {
      marginHorizontal: -NAVIENTY_NOW_LAYOUT.pageGutter,
      marginTop: 24,
  },
  activeOrdersRailContent: {
      flexDirection: 'row-reverse',
      gap: 12,
      paddingBottom: 5,
      paddingHorizontal: NAVIENTY_NOW_LAYOUT.pageGutter,
  },
  activeOrderCardShell: {
      flexShrink: 0,
  },
  activeOrderCard: {
      backgroundColor: NAVIENTY_NOW_COLORS.white,
      borderColor: '#E7E9E8',
      borderRadius: 24,
      borderWidth: 1,
      elevation: 0,
      minHeight: 190,
      paddingBottom: 17,
      paddingHorizontal: 17,
      paddingTop: 16,
      shadowColor: '#000000',
      shadowOffset: {
          width: 0,
          height: 1,
      },
      shadowOpacity: 0.025,
      shadowRadius: 4,
  },
  activeOrderCardPressed: {
      opacity: 0.94,
      transform: [{ scale: 0.994 }],
  },
  activeOrderTopRow: {
      alignItems: 'center',
      flexDirection: 'row-reverse',
      minHeight: 62,
  },
  activeOrderStoreArtwork: {
      alignItems: 'center',
      backgroundColor: NAVIENTY_NOW_COLORS.white,
      borderColor: '#ECEEED',
      borderRadius: 16,
      borderWidth: 1,
      height: 58,
      justifyContent: 'center',
      overflow: 'hidden',
      width: 58,
  },
  activeOrderStoreImage: {
      height: '100%',
      width: '100%',
  },
  activeOrderStoreImageLoading: {
      backgroundColor: '#F1F4F2',
      borderRadius: 14,
      height: '100%',
      width: '100%',
  },
  activeOrderStoreFallback: {
      fontSize: 25,
  },
  activeOrderStoreNameWrap: {
      alignItems: 'flex-end',
      flex: 1,
      justifyContent: 'center',
      marginRight: 12,
      minWidth: 0,
  },
  activeOrderStoreName: {
      color: NAVIENTY_NOW_COLORS.text,
      fontSize: 16,
      fontWeight: '900',
      lineHeight: 23,
      textAlign: 'right',
      width: '100%',
      writingDirection: 'rtl',
  },
  activeOrderFlow: {
      marginTop: 22,
  },
  activeOrderFlowRow: {
      alignItems: 'center',
      flexDirection: 'row-reverse',
      minHeight: 38,
      paddingHorizontal: 4,
  },
  activeOrderFlowStep: {
      alignItems: 'center',
      height: 38,
      justifyContent: 'center',
      width: 38,
  },
  activeOrderStepIconWrap: {
      alignItems: 'center',
      height: 34,
      justifyContent: 'center',
      position: 'relative',
      width: 34,
  },
  activeOrderConfirmationIcon: {
      backgroundColor: '#EFF1F0',
      borderRadius: 17,
  },
  activeOrderConfirmationIconReached: {
      backgroundColor: NAVIENTY_NOW_COLORS.primary,
  },
  activeOrderActiveHalo: {
      backgroundColor: NAVIENTY_NOW_COLORS.primary,
      borderRadius: 22,
      bottom: -5,
      left: -5,
      position: 'absolute',
      right: -5,
      top: -5,
  },
  activeOrderConnector: {
      backgroundColor: '#E4E6E5',
      borderRadius: 3,
      flex: 1,
      height: 5,
      marginHorizontal: 6,
      minWidth: 18,
      overflow: 'hidden',
      position: 'relative',
  },
  activeOrderConnectorFill: {
      backgroundColor: NAVIENTY_NOW_COLORS.primary,
      bottom: 0,
      left: 0,
      position: 'absolute',
      right: 0,
      top: 0,
  },
  activeOrderConnectorCurrentFill: {
      backgroundColor: NAVIENTY_NOW_COLORS.primary,
      borderRadius: 3,
      bottom: 0,
      position: 'absolute',
      right: 0,
      top: 0,
      width: '18%',
  },
  activeOrderCurrentStatus: {
      color: '#2A2C2B',
      fontSize: 18,
      fontWeight: '900',
      lineHeight: 26,
      marginTop: 18,
      textAlign: 'right',
      width: '100%',
      writingDirection: 'rtl',
  },
  compactEmptyCard: {
      alignItems: 'center',
      backgroundColor: NAVIENTY_NOW_COLORS.surface,
      borderRadius: NAVIENTY_NOW_LAYOUT.cardRadius,
      marginTop: 22,
      padding: 22,
  },
  compactEmptyTitle: {
      color: NAVIENTY_NOW_COLORS.text,
      fontSize: 15,
      fontWeight: '900',
      textAlign: 'center',
      writingDirection: 'rtl',
  },
  compactEmptyDescription: {
      color: NAVIENTY_NOW_COLORS.textSecondary,
      fontSize: 11,
      lineHeight: 18,
      marginTop: 5,
      textAlign: 'center',
      writingDirection: 'rtl',
  },
  loadingPageContent: {
      paddingBottom: NAVIENTY_NOW_LAYOUT.bottomNavigationHeight +
          35,
  },
  loadingHeader: {
      backgroundColor: NAVIENTY_NOW_COLORS.primary,
      minHeight: Platform.OS === 'android'
          ? (NativeStatusBar.currentHeight ?? 0) +
              88
          : 106,
      overflow: 'hidden',
      position: 'relative',
  },
  loadingCategories: {
      flexDirection: 'row-reverse',
      justifyContent: 'space-between',
      marginTop: 27,
      overflow: 'hidden',
  },
  loadingCategoryItem: {
      alignItems: 'center',
      width: 90,
  },
  loadingCategoryTile: {
      backgroundColor: '#EEEEF0',
      borderRadius: 23,
      height: 90,
      width: 90,
  },
  loadingCategoryLabel: {
      backgroundColor: '#F0F0F2',
      borderRadius: 5,
      height: 12,
      marginTop: 9,
      width: 58,
  },
  loadingMainCard: {
      backgroundColor: '#EFEFF1',
      borderRadius: NAVIENTY_NOW_LAYOUT.majorRadius,
      height: Math.round(232 * HOME_BANNER_HEIGHT_SCALE),
      marginTop: 30,
  },
  loadingExclusiveBanner: {
      backgroundColor: '#EFEFF1',
      borderRadius: NAVIENTY_NOW_LAYOUT.majorRadius,
      height: Math.round(232 * HOME_BANNER_HEIGHT_SCALE),
  },
  loadingSectionTitle: {
      backgroundColor: '#ECECEE',
      borderRadius: 7,
      height: 23,
      marginBottom: 16,
      marginLeft: 'auto',
      marginTop: 34,
      width: 170,
  },
  errorPageContent: {
      minHeight: '100%',
      paddingBottom: NAVIENTY_NOW_LAYOUT.bottomNavigationHeight +
          35,
  },
  errorContentShell: {
      alignItems: 'center',
      alignSelf: 'center',
      maxWidth: 430,
      paddingHorizontal: 24,
      paddingTop: 72,
      width: '100%',
  },
  fatalErrorIcon: {
      alignItems: 'center',
      backgroundColor: '#FFF0F0',
      borderRadius: 36,
      height: 72,
      justifyContent: 'center',
      width: 72,
  },
  fatalErrorIconText: {
      color: NAVIENTY_NOW_COLORS.error,
      fontSize: 35,
      fontWeight: '900',
  },
  fatalErrorTitle: {
      color: NAVIENTY_NOW_COLORS.text,
      fontSize: 22,
      fontWeight: '900',
      marginTop: 20,
      textAlign: 'center',
      writingDirection: 'rtl',
  },
  fatalErrorDescription: {
      color: NAVIENTY_NOW_COLORS.textSecondary,
      fontSize: 12,
      lineHeight: 21,
      marginTop: 9,
      textAlign: 'center',
      writingDirection: 'rtl',
  },
  fatalRetryButton: {
      alignItems: 'center',
      backgroundColor: NAVIENTY_NOW_COLORS.primary,
      borderRadius: 16,
      justifyContent: 'center',
      marginTop: 22,
      minHeight: 50,
      paddingHorizontal: 23,
  },
  fatalRetryButtonText: {
      color: NAVIENTY_NOW_COLORS.white,
      fontSize: 14,
      fontWeight: '900',
  }
});
