insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'now-media',
  'now-media',
  true,
  10485760,
  array[
    'image/webp',
    'image/jpeg',
    'image/png'
  ]::text[]
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create table if not exists now.media_migration_log (
  id bigint generated by default as identity primary key,
  entity_table text not null,
  entity_id text not null,
  field_path text not null,
  old_url text not null,
  new_url text not null,
  storage_path text,
  migrated_at timestamptz not null default now()
);

create index if not exists media_migration_log_entity_idx
  on now.media_migration_log (entity_table, entity_id);

alter table now.media_migration_log enable row level security;

revoke all
on table now.media_migration_log
from anon, authenticated;

grant select, insert
on table now.media_migration_log
to service_role;
